# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default.global.parameters]
stack_name = "youtube-uploader"
image_repositories = ["YoutubeVideoUploaderFunction=008082804869.dkr.ecr.us-west-1.amazonaws.com/tennisbuddies/youtube-video-uploader"]

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
region = "us-west-1"
parameter_overrides = "Environment=\"dev\""
s3_prefix = "youtube-uploader"

[default.sync.parameters]
watch = true
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
region = "us-west-1"
parameter_overrides = "Environment=\"dev\""
guided = true
s3_prefix = "youtube-uploader"

[default.package.parameters]
resolve_s3 = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

[prod.deploy.parameters]
stack_name = "youtube-uploader"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
region = "us-west-1"
parameter_overrides = "Environment=prod"
guided = true

[preview.deploy.parameters]
stack_name = "youtube-uploader"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
region = "us-west-1"
parameter_overrides = "Environment=preview"
guided = true
