AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  youtube-uploader

  A Lambda function that uploads video files from S3 to YouTube

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 900
    MemorySize: 1024

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - preview
      - prod
    Description: Environment (dev, preview, or prod)

Conditions:
  IsProd: !Equals [!Ref Environment, 'prod']
  IsPreview: !Equals [!Ref Environment, 'preview']

Resources:
  YoutubeVideoUploaderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: uploader_lambda/
      Architectures:
        - x86_64
      PackageType: Image
      Policies:
        - S3CrudPolicy:
            BucketName: !If 
              - IsProd
              - 'tennisbuddies-club-prod'
              - !If [IsPreview, 'tennisbuddies-club-prev', 'tennisbuddies-club']
        - S3CrudPolicy:
            BucketName: !If 
              - IsProd
              - 'tennisbuddies-club-thumbnails-prod'
              - !If [IsPreview, 'tennisbuddies-club-thumbnails-prev', 'tennisbuddies-club-thumbnails']
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !If 
                - IsProd
                - 'arn:aws:secretsmanager:us-west-1:008082804869:secret:TennisBuddies/YoutubeAPI-Prod-eBWbUu'
                - !If 
                  - IsPreview
                  - 'arn:aws:secretsmanager:us-west-1:008082804869:secret:TennisBuddies/YoutubeAPI-Prev-2UTaHW'
                  - 'arn:aws:secretsmanager:us-west-1:008082804869:secret:TennisBuddies/YoutubeAPI-cKJ3lH'
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !If
                - IsProd
                - 'arn:aws:secretsmanager:us-west-1:008082804869:secret:TennisBuddies/WebhookSecret-Prod-2Qrler'
                - !If
                  - IsPreview
                  - 'arn:aws:secretsmanager:us-west-1:008082804869:secret:TennisBuddies/WebhookSecret-Prev-sHxaTE'
                  - 'arn:aws:secretsmanager:us-west-1:008082804869:secret:TennisBuddies/WebhookSecret-CfK4H6'
      Environment:
        Variables:
          S3_BUCKET_NAME: !If 
            - IsProd
            - 'tennisbuddies-club-prod'
            - !If [IsPreview, 'tennisbuddies-club-prev', 'tennisbuddies-club']
          S3_THUMBNAIL_BUCKET_NAME: !If 
            - IsProd
            - 'tennisbuddies-club-thumbnails-prod'
            - !If [IsPreview, 'tennisbuddies-club-thumbnails-prev', 'tennisbuddies-club-thumbnails']
          YOUTUBE_API_SECRET_ID: !If 
            - IsProd
            - 'TennisBuddies/YoutubeAPI-Prod'
            - !If [IsPreview, 'TennisBuddies/YoutubeAPI-Prev', 'TennisBuddies/YoutubeAPI']
          AWS_SECRETS_MANAGER_REGION: 'us-west-1'
          WEBHOOK_SECRET_ID: !If 
            - IsProd
            - 'TennisBuddies/WebhookSecret-Prod'
            - !If [IsPreview, 'TennisBuddies/WebhookSecret-Prev', 'TennisBuddies/WebhookSecret']
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./uploader_lambda
      DockerTag: python3.9-v1

Outputs:
  YoutubeVideoUploaderFunction:
    Description: "YouTube Video Uploader Lambda Function ARN"
    Value: !GetAtt YoutubeVideoUploaderFunction.Arn
  YoutubeVideoUploaderFunctionIamRole:
    Description: "Implicit IAM Role created for YouTube Video Uploader function"
    Value: !GetAtt YoutubeVideoUploaderFunctionRole.Arn
