AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  youtube-uploader

  A simple Lambda function that prints "Hello World!" when invoked directly

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 256

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Environment (dev or prod)

Conditions:
  IsProd: !Equals [!Ref Environment, 'prod']

Resources:
  YouTubeUploaderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: uploader_lambda/
      Architectures:
        - x86_64
      PackageType: Image
      Policies:
        - S3ReadPolicy:
            BucketName: !If [IsProd, 'tennisbuddies-club-prod', 'tennisbuddies-club']
      Environment:
        Variables:
          S3_BUCKET_NAME: !If [IsProd, 'tennisbuddies-club-prod', 'tennisbuddies-club']
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./uploader_lambda
      DockerTag: python3.9-v1

Outputs:
  YouTubeUploaderFunction:
    Description: "YouTube Uploader Lambda Function ARN"
    Value: !GetAtt YouTubeUploaderFunction.Arn
  YouTubeUploaderFunctionIamRole:
    Description: "Implicit IAM Role created for YouTube Uploader function"
    Value: !GetAtt YouTubeUploaderFunctionRole.Arn
